os: osx
language: bash

git:
  depth: 5

before_script:
  - brew install wxmac
  - brew install gtk+3
  - brew install automake
  - brew install autoconf
  - brew install m4
  - brew install perl
  - autoreconf
  - ./configure

script:
  - automake
  - make
