language: bash

git:
  depth: 5

before_script:
  - sudo apt-get update
  - sudo apt-get install libwxgtk2.8-dev libwxgtk2.8-dbg
  - sudo apt-get install gtk2.0
  - sudo apt-get install automake
  - ./configure

script:
  - make
