language: bash

git:
  depth: 5

before_script:
  - sudo apt-get update
  - sudo apt-get install libwxgtk2.8-dev libwxgtk2.8-dbg
  - sudo apt-get install gtk2.0
  - sudo apt-get install automake
  - sudo apt-get install autoconf
  - sudo apt-get install m4
  - sudo apt-get install perl
  - autoreconf
  - ./configure

script:
  - automake
  - make
  - sudo make install
