language: bash

git:
  depth: 5

before_script:
  - curl http://apt.wxwidgets.org/key.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install libwxgtk2.8-dev libwxgtk2.8-dbg
  - ./configure

script:
  - ./compile
